#ifndef __ASM_OFFSETS_H__
#define __ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by /home/prof/kitten/Kbuild
 *
 */

	
#define TI_FLAGS 192 /* offsetof(struct task_struct, arch.flags)	// */
	
#define TSK_ARCH_THREAD_CPU_CONTEXT_SP 296 /* offsetof(struct task_struct, arch) + offsetof(struct arch_task, thread) + offsetof(struct thread_struct, cpu_context) + offsetof(struct cpu_context, sp)	// */
#define TSK_ARCH_THREAD_CPU_CONTEXT_USERSP 320 /* offsetof(struct task_struct, arch) + offsetof(struct arch_task, thread) + offsetof(struct thread_struct, cpu_context) + offsetof(struct cpu_context, usersp)	// */
#define TSK_ARCH_FLAGS 192 /* offsetof(struct task_struct, arch) + offsetof(struct arch_task, flags)	// */
	
#define S_X0 0 /* offsetof(struct pt_regs, regs[0])	// */
#define S_X1 8 /* offsetof(struct pt_regs, regs[1])	// */
#define S_X2 16 /* offsetof(struct pt_regs, regs[2])	// */
#define S_X3 24 /* offsetof(struct pt_regs, regs[3])	// */
#define S_X4 32 /* offsetof(struct pt_regs, regs[4])	// */
#define S_X5 40 /* offsetof(struct pt_regs, regs[5])	// */
#define S_X6 48 /* offsetof(struct pt_regs, regs[6])	// */
#define S_X7 56 /* offsetof(struct pt_regs, regs[7])	// */
#define S_LR 240 /* offsetof(struct pt_regs, regs[30])	// */
#define S_SP 248 /* offsetof(struct pt_regs, sp)	// */
#define S_PSTATE 264 /* offsetof(struct pt_regs, pstate)	// */
#define S_PC 256 /* offsetof(struct pt_regs, pc)	// */
#define S_ORIG_X0 272 /* offsetof(struct pt_regs, orig_x0)	// */
#define S_SYSCALLNO 280 /* offsetof(struct pt_regs, syscallno)	// */
#define S_FRAME_SIZE 288 /* sizeof(struct pt_regs)	// */
	
	
	
	
#define PAGE_SZ 4096 /* PAGE_SIZE	// */
	
	
	
#define NSEC_PER_SEC 1000000000 /* NSEC_PER_SEC	// */
	
	
#define TVAL_TV_SEC 0 /* offsetof(struct timeval, tv_sec)	// */
#define TVAL_TV_USEC 8 /* offsetof(struct timeval, tv_usec)	// */
#define TSPEC_TV_SEC 0 /* offsetof(struct timespec, tv_sec)	// */
#define TSPEC_TV_NSEC 8 /* offsetof(struct timespec, tv_nsec)	// */
	
#define TZ_MINWEST 0 /* offsetof(struct timezone, tz_minuteswest)	// */
#define TZ_DSTTIME 4 /* offsetof(struct timezone, tz_dsttime)	// */
	
#define ARM_SMCCC_RES_X0_OFFS 0 /* offsetof(struct arm_smccc_res, a0)	// */
#define ARM_SMCCC_RES_X2_OFFS 16 /* offsetof(struct arm_smccc_res, a2)	// */
#define ARM_SMCCC_QUIRK_ID_OFFS 0 /* offsetof(struct arm_smccc_quirk, id)	// */
#define ARM_SMCCC_QUIRK_STATE_OFFS 8 /* offsetof(struct arm_smccc_quirk, state)	// */
#define __NR_syscall_max 534 /* sizeof(syscalls) - 1	// */

#endif
